version: "3"
services:
    api:
        build: ./backend/api
        container_name: 'api-cryptocoins'
        command: sh -c 'pip3 install -r api/requirements.txt; flask run'
        ports: 
            - '5000:5000'
        volumes:
            - './backend/api:/backend/api'
        depends_on:
            - 'db_cryptocoins'

    db_cryptocoins:
        container_name: 'db_cryptocoins'
        image: mongo
        ports:
            - "27017:27017"

    # frontend:
    #     build: ./frontend
    #     container_name: 'cryptocoins-ui'
    #     command: sh -c 'npm install; npm start'
    #     ports:
    #         - '3000:3000'
    #     volumes:
    #         - ./frontend/cryptocoins-ui:/frontend/cryptocoins-ui
    #     depends_on:
    #         - "api"
    #     stdin_open: true
    #     tty: true
